"""Add email verification

Revision ID: 09919040a7bb
Revises: a284345e40cd
Create Date: 2025-04-12 16:14:11.611235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09919040a7bb'
down_revision = 'a284345e40cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
